### ISSUE TITLE
How to properly build your applications in VS2017

### ISSUE THREAD

**Issue by morrowd** [zodiacon/SystemExplorer#1]
This isn't an issue, but a request for some help/documentation on how to properly build your applications, not just SystemExplorer but all your projects, in Visual Studio 2017 or earlier if necessary. 

I follow your AllTools repo, but would like to build your apps in my own development environment more frequently if possible.

Thanks,

Dax

**Comment by zodiacon** [comment]
Hi Dax,
Most projects should build fine just by opening the solution in VS 2017 and selecting Build Solution. SystemExplorer is different at the moment because I use Syncfusion assemblies from my GAC and not the Nuget packages (some don't exist yet). I hope to fix that soon.
Let me know if you have any issues with other projects.

**Comment by morrowd** [comment]
Pavel,

Thank you for the response. When I open PEExplorer in VS 2017 and attempt to build the solution I get the following errors and warnings:

Errors

The tag 'KeyTrigger' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactions'. Line 32 Position 22.         PEExplorer            PEExplorer\PEExplorer\Views\Tabs\ExportsTabView.xaml  32

The tag 'KeyTrigger' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactions'. Line 37 Position 18.         PEExplorer            PEExplorer\PEExplorer\Views\Tabs\GeneralTabView.xaml 37


Warnings

Could not resolve this reference. Could not locate the assembly "Microsoft.Expression.Interactions, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    PEExplorer

The referenced component 'Microsoft.Expression.Interactions' could not be found.       PEExplorer

Regards,

Dax

Dax Morrow

**Comment by zodiacon** [comment]
The KeyTrigger type comes from the Microsoft.Expression.Interactions assembly. Do you see it in the list of references? If not, add it and see if this solves the issue. It's weird since it is part of the project.

**Comment by morrowd** [comment]
It looks like it is no longer included in the default Visual Studio https://developercommunity.visualstudio.com/content/problem/198075/microsoftexpressioninteractions-is-missing-from-vi.html

I’ll try to add it and see if my issues are resolved.

Thanks,

Dax

**Comment by morrowd** [comment]
Fixed! I just needed to install “Blend for Visual Studio SDK for .NET“ via the Extensions and Updates under Tools.

Thanks,

Dax

Dax Morrow
