### ISSUE TITLE
The process's commandline is empty.

### ISSUE THREAD

**Issue by BeneficialCode** [zodiacon/SystemExplorer#11]
I found that the process's commandline is empty when it runs on the Windows 7. Then I try to use the ProcessHacker. It correctly gets the process's commandLine. After that, I have found the function implementation is PhGetProcessCommandLine. 
ProcessCommandLineInformation only supports WindowsVersion >= WINDOWS_8_1.

**Comment by zodiacon** [comment]
Yes, I'm aware...
I was just too lazy to implement it for earlier Windows versions :)
