### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by johnjohnsp1** [zodiacon/SystemExplorer#3]
Hello, i'm getting this error during compilation phase:

"C:\temps\ObjectExplorer\ObjectExplorer.sln" (default target) (1) ->
"C:\temps\ObjectExplorer\ObjectExplorer\ObjectExplorer.vcxproj.metaproj" (default target) (2) ->
"C:\temps\ObjectExplorer\KObjExp\KObjExp.vcxproj" (default target) (3) ->
(ValidateNTTargetVersion target) ->
  C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.common.targets(255,5): error MSB4062: The "ValidateNTTarge
tVersion" task could not be loaded from the assembly C:\Program Files (x86)\Windows Kits\10\build\bin\Microsoft.DriverK
it.Build.Tasks.16.0.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Windows Kits\10\build\bin\Micr
osoft.DriverKit.Build.Tasks.16.0.dll' or one of its dependencies. The system cannot find the file specified. Confirm th
at the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task
contains a public class that implements Microsoft.Build.Framework.ITask. [C:\temps\ObjectExplorer\KObjExp\KObjExp.vcxpr
oj]

using command line vsstudio2019 
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28319 for x64
Microsoft (R) Incremental Linker Version 14.24.28319.0

anything i do wrong ?
thanks

**Comment by zodiacon** [comment]
Do you have the latest Windows Driver Kit installed?
Build the Release version first

**Comment by johnjohnsp1** [comment]
Yes, I have checked and using wdk 10.0.8362.0

Is that correct ?

**Comment by zodiacon** [comment]
Yes, that should be ok.

**Comment by zodiacon** [comment]
Check the driver's project properties to make sure

**Comment by zodiacon** [comment]
Also, I only build the x64 version

**Comment by johnjohnsp1** [comment]
Yes I have checked and match the Windows SDK 10.0.8362.0

**Comment by johnjohnsp1** [comment]
now i have this output:

c:\temp\objectexplorer\kobjexp\kobjexp.cpp(1): fatal error C1083: Cannot open include file: 'ntifs.h': No such file or
directory [C:\temp\objectexplorer\KObjExp\KObjExp.vcxproj]

**Comment by zodiacon** [comment]
It seems the WDK is not installed properly. Note WDK not SDK

**Comment by johnjohnsp1** [comment]
i forgot to mention that im using the command line build tools 2019 not the gui interface.
now once did updated all the tools within the same folder if i compile getting this:

C:\temp\objectexplorer\ObjectExplorer\MainFrm.cpp(711,2): error C3861: 'UIRemove': identifier not found [C:\temp\object
explorer\ObjectExplorer\ObjectExplorer.vcxproj]

the command used is: "msbuild ObjectExplorer.sln"

**Comment by zodiacon** [comment]
You can remove the RemoveBand function altogether.
I'll remove it in my next commit

**Comment by zodiacon** [comment]
just remove the body and return false

**Comment by johnjohnsp1** [comment]
it worked, thanks i will add a screenshot since once executed ask me to install a driver kernel, i press yes and appear a second error messagebox, once clicked ok the explorer start. anything related to the removed line ?

thanks once more for the help
![objectexplorer](https://user-images.githubusercontent.com/1888855/79257067-5df24800-7e89-11ea-8f7b-4484b01e1b1f.png)

**Comment by zodiacon** [comment]
Yeah, you have to be in test signing mode, since the driver is not signed...
bcdedit /set testsigning on
from an admin command window and restart

**Comment by johnjohnsp1** [comment]
Thanks, its works now.
Appreciate the help and for sharing the code
