### ISSUE TITLE
process handle's Acess is not correct.

### ISSUE THREAD

**Issue by BeneficialCode** [zodiacon/SystemExplorer#6]
ObjExpCore lib:
ProcessModuleTracker::IsRunning()
when I try to use the pid to construction ProcessModuleTracker, I discover this mistake.
``WinSys::ProcessModuleTracker::ProcessModuleTracker(DWORD pid)``
OpenProcess() the first argument should  combine with | SYNCHRONIZE

https://docs.microsoft.com/zh-cn/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject?f1url=%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(SYNCHAPI%252FWaitForSingleObject);k(WaitForSingleObject);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue

**Comment by zodiacon** [comment]
You're right. Fixed.
