### ISSUE TITLE
support for NT 5.1

### ISSUE THREAD

**Issue by andika207** [zodiacon/SystemExplorer#7]
hello
this utility doesn't run on Windows XP.
hopefully you compile it for older Windows versions too

**Comment by blackcrack** [comment]
jepp would nice if have the 5.1 compatibility and it run in WinXP too.
i think at Reactos.org (where is 5.1 at moment in developing)

best

**Comment by zodiacon** [comment]
Sorry, that won't happen, since I'm using some APIs which don't exist on XP. Since XP is no longer supported, I won't either.
