### ISSUE TITLE
Add a Prozess Tree for show the prozessdepencies

### ISSUE THREAD

**Issue by blackcrack** [zodiacon/SystemExplorer#8]
1. Cool to be start a new System explorer !!!!!! :heart: :+1:  :100:  :heart: 

Add a Prozess Tree for show the prozessdepencies and able for/ possibility to arrange with an small bar/strip on top of the whole prozesses like in Totalcommander the Filelisting ˄/˅ (up/down arrangement of the files ) on top.

![Screen 00000](https://user-images.githubusercontent.com/7925717/127730794-1a5ae1c6-9042-4d3d-8c07-8abb61e7ce97.jpg)

best  
Blacky

**Comment by zodiacon** [comment]
It exists in the System/Process Tree menu.

**Comment by blackcrack** [comment]
@zodiacon i have only see the screenshots, i must it download and test it out..
because the screenshot  not up to date have i let myself be deterred to try it out right away..
and have it not see.. Thank you for your patience :smile:
